image:
  file: Dockerfile.gitpod
tasks:
  - env:
      CHAT_ID: "-1001498263454"
      REDIS_URL: "redis://:@localhost:6379"
  - command: poetry install
    env:
      PIP_USER: "false"
  - command: redis-server
github:
  prebuilds:
    addComment: true
