image:
  file: Dockerfile.gitpod
tasks:
  - before: export PIP_USER=false
    init: poetry install
  - command: redis-server
github:
  prebuilds:
    addComment: true
ports:
  - port: 6379
    onOpen: ignore
