language: python
python:
  - "3.9"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run hy src/main.py
env:
  - CHAT_ID="-1001498263454" REDIS_URL="redis://:@localhost:6379"
services: redis-server
