language: python
python:
  - "3.9"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run hy src/main.hy
env:
  - CHAT_ID="-1001498263454"
  - REDIS_URL="redis://:@localhost:6379"
cache:
  directories:
    - /home/travis/.cache/pypoetry/virtualenvs
services: redis-server
