FROM gitpod/workspace-full

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 - && \
    wget -q https://github.com/dhall-lang/dhall-haskell/releases/download/1.39.0/dhall-json-1.7.7-x86_64-linux.tar.bz2 && \
    wget -q https://github.com/dhall-lang/dhall-haskell/releases/download/1.39.0/dhall-lsp-server-1.0.15-x86_64-linux.tar.bz2 && \
    tar xf dhall-json-1.7.7-x86_64-linux.tar.bz2 -C /usr/local && \
    tar xf dhall-lsp-server-1.0.15-x86_64-linux.tar.bz2 -C /usr/local

# Add Poetry to PATH.
ENV PATH="${HOME}/.local/bin:${PATH}"
