[tool.poetry]
name = "drmhbot"
version = "0.1.0"
description = ""
authors = ["Julia <juliariety@gmail.com>"]
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
beautifulsoup4 = "^4.9.3"
python-telegram-bot = "^13.0"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
mypy = "^0.790"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
