version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  test_run:
    docker:
      - image: cimg/python:3.9
      - image: redis:6.2
    steps:
      - checkout
      - run:
          name: Check if sources.dhall is newer than sources.json
          command: |
            if [ "source.dhall" -nt "source.json" ]; then
              echo "source.dhall is newer than source.json! Did you forget to run regenerate_sources.sh?"
              exit 1
            fi
      - run:
          name: Wait for Redis to be available
          command: |
            sudo apt-get update
            sudo apt-get install -y redis-tools

            while ! redis-cli ping 2>/dev/null ; do
                    echo -n "."
                    sleep 0.1
            done
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run the bot
          command: poetry run hy src/main.hy
          environment:
            CHAT_ID: "-1001498263454"
            REDIS_URL: redis://:@localhost:6379
workflows:
  test_run:
    jobs:
      - test_run
