version: "3.9"
services:
  bot:
    image: ghcr.io/heyajulia/drmhbot
    env_file: .env
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
  redis:
    image: redis:alpine
