version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # From a comment by @chrmarti on microsoft/vscode-remote-release#2524:
    # https://github.com/microsoft/vscode-remote-release/issues/2524#issuecomment-627759728
    command: /bin/sh -c "while sleep 1000; do :; done"
    expose:
      - 6379
    volumes:
      - ..:/workspace:cached
  redis:
    image: redis:alpine
