version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # From microsoft/vscode-remote-release#2524: https://git.io/JD9mC
    command: /bin/sh -c "while sleep 1000; do :; done"
    expose:
      - 6379
    volumes:
      - ..:/workspace:cached
  redis:
    image: redis:alpine
