#!/usr/bin/env python3

import json


def tidy(sources):
    for source in sources:
        domains = sources[source]

        try:
            domains.sort()
        except AttributeError:
            pass

    return sources


def main():
    with open("sources.json", "r+") as f:
        sources = json.load(f)
        tidied_sources = tidy(sources)

        f.seek(0)

        json.dump(tidied_sources, f, indent=2, sort_keys=True)

        f.write("\n")



if __name__ == "__main__":
    main()
