#!/usr/bin/env python3

import json


def sort_dict(d):
    return {k: v for k, v in sorted(d.items())}


def tidy(sources):
    multi_domains = {}

    for name in list(sources):
        domains = sources[name]

        if isinstance(domains, list):
            multi_domains[name] = sorted(domains)
            del sources[name]

    return sort_dict(sources) | sort_dict(multi_domains)


def main():
    with open("sources.json", "r+") as f:
        sources = json.load(f)
        tidied_sources = tidy(sources)

        f.seek(0)

        json.dump(tidied_sources, f, indent=2)

        f.write("\n")


if __name__ == "__main__":
    main()
