name: Prebuild devcontainer
on:
  push:
    paths:
      - .github/workflows/*
      - .devcontainer/*
  workflow_dispatch:
jobs:
  prebuild_devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: heyajulia
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
          file: .devcontainer/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
