name: Test run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - name: Add Poetry to PATH
        run: echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV
      - name: Install dependencies
        run: poetry install
      - name: Run the bot
        run: poetry run hy src/main.hy
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: "-1001498263454"
          REDIS_URL: redis://:@localhost:6379
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
